### ISSUE TITLE
Rename command to the shorter one

### ISSUE THREAD

**Issue by dtan4** [wantedly/api-server-generator#5]
## WHY
`api-server-generator` command is too long to type, I think.
Command name should be short and easy to remember as possible.

## WHAT
Rename `api-server-generator` command to the shorter one.

IMO `apig` (abbreviation of `API-server-Generator`) seems to be good. This is short enough and easy to remember. Additionally, at this time there seems to be [no project named `apig` on GitHub](https://github.com/search?utf8=%E2%9C%93&q=%27apig%27&type=Repositories&ref=searchresults). This name has uniqueness too.

**Comment by dtan4** [comment]
@munisystem FYI: After https://github.com/wantedly/api-server-generator/pull/8 is merged, I'm going to rename this repository and all import paths.

**Comment by munisystem** [comment]
@dtan4 OK. Fix #8 ASAP.
